Issue 1 create an entry
Steve-A-Dore/code-journal pull request #5
Opened 2021-03-31 04:31 UTC by Steve-A-Dore

![image](https://user-images.githubusercontent.com/51938797/113090694-33cf8e00-919f-11eb-98de-ffcf8b886878.png)

2021-03-31 23:48 UTC, Steve-A-Dore commented
ENTER DATA
![image](https://user-images.githubusercontent.com/51938797/113224641-b9efe100-9240-11eb-8ae7-f804e45d37a3.png)

After ENTRY of PREVIOUS DATA
![image](https://user-images.githubusercontent.com/51938797/113224666-c5430c80-9240-11eb-9b88-0c2d48afdebf.png)


All done using incognito browser window. 

MOBILE VIEW - INCOGNITO
![image](https://user-images.githubusercontent.com/51938797/113224714-d9870980-9240-11eb-9257-712c741139ad.png)

2021-04-01 00:11 UTC, codingcodymiller requested changes

2021-04-01 00:11 UTC, codingcodymiller commented on js/data.js
> +  event.submit();
This can be removed

2021-04-01 00:15 UTC, codingcodymiller approved these changes

2021-04-01 00:35 UTC, merged